sonelokimab2 = """
>Sonelokimab2_IL17F_Heavy_Chain_1
EVQLVESGGGLVQPGGSLRLSCAASGRTYDAMGWLRQAPGKEREFVAAISGSGDDTYYADSVKGRFTISRDNSKNTLYLQMNSLRPEDTAVYYCATRRGLYYVWDANDYENWGQGTLVTVSS
>Sonelokimab2_IL17F_Light_Chain_1
na
"""
