envafolimab = """
>Envafolimab_PDL1-CD274_Heavy_Chain_1
QVQLVESGGGLVQPGGSLRLSCAASGKMSSRRCMAWFRQAPGKERERVAKLLTTSGSTYLADSVKGRFTISRDNSKNTVYLQMNSLRAEDTAVYYCAADSFEDPTCTLVTSSGAFQYWGQGTLVTVSS
>Envafolimab_PDL1-CD274_Light_Chain_1
na
"""
