gocatamig2 = """
>Gocatamig2_DLL3_Heavy_Chain_1
EVQLVESGGGLVQPGGSLTLSCAASSSSVSLLSLAWYRQAPGKKRELVAGISDDGSIVYMDSVKGRFTISRDNAKNSVYLQMNSLRAEDTAVYYCYAYSWITRSPYWGQGTLVTVSS
>Gocatamig2_DLL3_Light_Chain_1
na
"""
