"""
Rosalind Problem: GC - Computing GC Content
Problem URL: http://rosalind.info/problems/gc/
Location: Bioinformatics Stronghold
Author: Bunsree Patel
Date: October 28, 2025
"""

"""GC-content of a DNA string is given by the percentage of symbols in the string that are 'C' or 'G'.
The reverse complement of any DNA string has the same GC-content.

DNA strings must be labeled when they are consolidated into a database.
A commonly used method of string labeling is called FASTA format. 
The string is introduced by a line that begins with '>', followed by some labeling information.
Subsequent lines contain the string itself; the first line to begin with '>' indicates the label of the next string.

Rosalind's implementation included labeling by the ID 'Rosalind_xxxx', where 'xxxx' denotes a four-digit code between 0000 and 9999."""

"""Sample Dataset Problem

    Given: At most 10 DNA strings in FASTA format (of length at most 1 kbp each).

    Return: The ID of the string having the highest GC-content, followed by the GC-content of that string.
    Rosalind allows for a default error of 0.001 in all decimal answers unless otherwise stated.

Note on Absolute Error: """

from DNAToolkit import parse_fasta, gc_content

# Sample FASTA input
fasta_input = """>Rosalind_6404
CCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCCTCCCACTAATAATTCTGAGG
>Rosalind_5959
CCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCTATATCCATTTGTCAGCAGACACGC
>Rosalind_0808
CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGACTGGGAACCTGCGGGCAGTAGGTGGAAT"""

# Parse the FASTA
fasta_dict = parse_fasta(fasta_input)

# Find the sequence with the highest GC content
max_id = None
max_gc = 0.0

for seq_id, dna_seq in fasta_dict.items():
    gc = gc_content(dna_seq)
    if gc > max_gc:
        max_gc = gc
        max_id = seq_id

# Print final answer
print(max_id)
print(f"{max_gc:.6f}")

"""Output: 
Rosalind_0808
60.919540"""


"""Actual Dataset Problem"""

from DNAToolkit import parse_fasta, gc_content

# Sample FASTA input
fasta_input = """>Rosalind_8044
ACCAAATAAGAATTGCGGTCATCTGTTAAAGGGCTGAGGACTTCGGTGTTGGCCGAACGG
CGTAACGCAATTGGCCCTGACGGTTGATACGACCTGTCGGGGTGTCTTCGCCTTACATAG
TTTTTCACCATCGGGACCAGACAAAGTCAGAAGTTCACCGCTTTAAAAAGGGGAAGGACC
CAAACAAGGCTGCTTCCCCCACTGTAGCTGGTTTCTTTCTCGCCGTGGCTGGCAACAGTT
TATCAGTAGCGCCACAGAAGCATTACACATCGGGCCAGTTCCTCGGAGCGAACGGCGGAG
ACGCGTCTGAAAACTAGCTCTCGATGCCCTCGGCACGGGGCGCGTCCTAACAAACAAGTA
GCTGACGCGGCCGCTTAAACACAAGGTTACCATTCCTCGAATTCTTTCTCAGGTCGTGCA
ATTTTCTATACATATGAACGGGGGCGCAGCCGCTGAAATGGTGTATGGCCCCGAACCGCT
ATTAGTCGGGCCCGAGCGCAATTGCGCCTAAATTTCTTTGATTCGGAACCCGACTGAAAG
TTTCCGGAACGTGGGGACGGGCATAGGGGACGGTGCGAGAATTGAATCACCCAACCGGCA
ACAGAGCAATGTCCCGTGCGAGGTACCAACCCTGAGTGGCAGAGGGCTAGGGCGTCTATA
GACCATCTTGCTAAATGGGTTATTTTAACCATAACTCGGCATGCATAGAAGTACCCCCCC
AGTCCAGCTAACGGCACAGGGTTGTCACAGCACCGCCCAGCCACTACGCTCCACTCTCGC
GCTTACCCATATTGCTAGCATAACGCGTCTCGACGGCAGTTCGGGACTTCCTCGACCTGC
CCCTTCTCCTCAGGCACACCCCCGCGAACACGGGTCCGGACTCCGTGGATTCGAACGCGT
GCCAATCTGTAAA
>Rosalind_9283
TCCAAGGAAGAATTTAACAATGTTCAGGAAGTGAAGAAGATAGACTCTTTCCTCTACCTC
CCAGTCAGGTCGCGACTTGACCGATCTATTTAGAAGTCCTACATTTGACAGTACGAGGCC
GTGTGCCCTTACTGTGCCAACTAAAAGAACGAGTAACGTAACATTCGTACGAGTTAATTT
CGCACCATCAGCATGACCTGGCAGGAAACGATTCAGACTGCGAACAGGGACCTGAAGGGA
AGTGTGACGTCGGGGGTCCCATTCTGTGTTCCGGGAAACGCGAGTCCGTTTATGTCTAGC
GGCCTTAATGGAATGTTCAATAGCCGTTACGAACATGAAAATCCTAAATGGTGGAAATAT
GCTACATCCGGGTTCGCTTCATAGGGCGGATCTCTGAAAGTCGCATCAATTCGTAGCAGA
CCTTAGACGGGCTGATTCAGGTGATACCATATGCGCAAGACTCTGGCGGAAAAGCTACAA
TCTCAACAGCCACTAGAATCTCATAGTGTGAAACGGAAGAGGTAGGCGTGCGTTGGTCAC
CCTTATCAGGTGGAAGGCCCATGCACTTGTTGGTCCTTAGTTTTGCGTTGTCATTTTGCT
TCGTCTGATGTTCATGTTGACCGACTTGCGGTTAGCAACTAGATCCGGATATAAACAATT
GGCGCCCACCTGGGCGTCAGGAACAGCAGTTTATATCTATTTTACAGTACCCCCGTGATG
CACTCGAAGCTGACCTACTGAGATGCGCGATTATTTGCTTCCTTCGTCGCCCGCGCGAAT
CACCTCCACACGGGACTACGATATCATACGAGCAACTTGAATGGTTGTCAATCAGGTCAC
TTGTGAAAAAATCAGCGATCTTAGCCATGGATCGAGACCCATACCCAGAAATGAAAACAT
CCTCACTAGTGCCTCCACA
>Rosalind_2393
GCTGTATGCCGTATGTGTCGGCACACATTAGTCTGTGGAAGATGGTACCACCTCCATTGG
CCGTCAGTGTAACATGACCACAACACCCACTCGTATTAGTTGGACAGCGGTGGTAGGGGG
TGAGGTTCGGTAGTAGGTAATAAATAACATATCAATATGTCTATGTCACACTTCCGGTAA
AGTACAGAGCCCAGTGAGCTCAACCAAAGGCGTAGTTCTTACTTGTGGGATTAGCCAACG
TCGCAGGCTCATCAAGCCTGCAAAAAAGTAGGATCCCCCCACGGAGTCCAGATAGTTCCG
ACCGAAATATCAATACACACGAGCAGGTTGAACGGGGGAGCCGCTGACTCGTAAACAGAT
AACCTGGCGTTGCTTTATCAGAACAATCATTATGTATGAGATATGAACCAGTCGTACAGG
AAAAGCATTACATAACGGCGTACCGTGGTGCAAAATGCATCATAACCTAATTTTGGGCAG
AACCGACTCGTGACTCCAAACGGCCGCCCGTTTGCTGTAGGGTCCGATAACGGGCTCGCC
GGACTGCGCTTCAAAGGAGTGTGCTCGCCCCTTTTTACCCCTCCCAAACGAAGAATGAGG
GGTACGCCCCAGTTGTGAAACGCTAGCAAATACATCCCGGTCGCGTCATACTGAGTGAAA
TTGGGCCGTTCGTCGGAAGAACGGGGGAGAACGGTTATTGAACGTTCCCGTCACGCATCA
CGCCAATCGGTGGTTGCTTCTACTCCAAATCAGAGTCGAAACCTGCAGTCAGCCGCACGC
ATCAGGTTATAATACCAGCCAATCCCTTGCCGGGTCCGGGCTACGGGGAAGCCCCCTCTC
GACAGTAGGAACCTGACCCCTAAGATCGTTTCAAGTCTCCGAACGTTAGATGAACGCGCT
CCATATGCCGCGCAATCAATTCTTATTGTGCCA
>Rosalind_7640
GCCCGCCGCACAGTAAAACATCTCGAGCTATGTTTAATTCACCATGTAAATAGTTTCCCC
CTGAATGGGGCGTGATCTGCTTATCAATACGGCGGTCGAAACCCTCCGCTATCGCAAGTC
TAAATCGTCTGAAGAAACAAATCCGGTAGCTGTAAGACACAGGGTCATACTCCCAACTGA
TTTCTTAAACGGGGTTAGTCACTGTTACAAGCTCCCGCGCTCGTTAAGAGGATTCTGGGT
TGAGGTACTACCCGCTTGGGCAGAATTAATAACTTTCGTGTAACGGACGGAAATCGTAGT
CTTACTAGGTAGATCAATATTGCTAACATCGATTAGCCAGGAGAACGCATGTGGTTTGAA
GAGTTTGGCGTCAAAGGTGTCAAACCGAGCGCTGGAACTCTGTTACTTATGTGATATGGA
ACTAGCGACCTATTCGAGGCGTGCCTTGGGGACGCGAAGAGCTATGCTGGACCTCTGTGG
TCGCATTCCTCGGCCAGGACCTCTAAACTTCCCCCTCGCTGAAGAGGCGCGATTACAACG
TCTACATGGTCTCTTGTAGTGGCTTTGTAGCGGACGCCCCAACGCGGTCTATTGTACAAG
TGTAGCACTTGAACATATTAATCCGAATCGGATCTTGAGCCACGCCTAAATAATTTCATG
GCTACAAACGACTATGGCCGGTCATCGATTTGCAGTAGAATCCTTGATAATACTGTGCCG
CCGATTATGGTGGCCCCCGCTCCCATAGGCACTAAAGCATGAAATGGTAATATTCCCTAT
GTCCAGTCATTAGTACATAATTTATCTGGTCGCTTTTCGGCCCGCAACGGCTAGTAAGCA
CTCAGGGCTAAGTGTATG
>Rosalind_3188
ACATGTCGGAGAACTCCGAGCCACATGGTGGGGTGTATGCCTTCTGAACCGAATGCCGGC
TTATGTCTGCAGCGATTTGCCATATACTCGTACTAGCTTAAATACCTAAAGGTTCCTAAT
GGTCTACTGCGGGAACGACTCCCACTCAACTGCGGTCTCATCTGATATGGTTGTCGGAAG
TGAATAAGCGTGCTTTGGCCCTCCAAATGGAAGAGGACCCGCAGAATTTGGTACAGGGTA
ACCAAGTAGCGGCTCCGGTCTCACGAATGCTTCCGCTTTACGGAGAGTCAGTTTTAACAG
TAAGAGACAAGCCATGACCCGCCGCATTTTGGGCATATTCGAGATCGTCCTCTGACCGAG
ATACAAACCTTTAAGCCAGCAGCCCTTTATTCCTGACCGCAACAAGAGACTGGCCACTAT
GTTTAACGGTGCAAACTGTATCAGAGTGTGTATGGCCTATGACTTGTACTAGAGGCCCTA
GTGTTTCTACAGCGCTAGCGCCTGCCAGGTACCACAACATTTAACCTGCGTGGTTCATAA
CAGCTGAACACGTACGTTCAGTGCGGTCAGCCACAATCATGAACTGCGCCTCTGCCGGAT
AGCAGGATCCGCCTACAATCTGCCACCGACAACTTAGGCTTATAAGATACTGTTCTATGT
CAGTTCCGAACCGGCGGACCAGAGTTTGGAGTATTCAACTTACCTAGCCACGCTATCGTA
TCTCGCCAATTTTCATGACAGTGGCACTCGTGCCAAGGCTTTACGAGTACTATCAACAAC
GTGACGCTTCGGTACGGTCGAGAGCTCAACAAAACCGAGTTAAGATTAATTCACATAGCC
GACACGCGCGTCGACTTGATTGATCTGGCCCTATTCGGATAAATAGGGGAAATCCTACAC
CGCATATAAGCCAAAGACTGAGCTTGGGC"""

# Parse the FASTA
fasta_dict = parse_fasta(fasta_input)

"""Converts a raw FASTA-formatted string into a Python dictionary.
Keys = sequence IDS (e.g., 'Rosalind_8044')
Values = DNA sequences (continuous strings of A, T, G, C).

Example output structure:
{  
    "Rosalind_8859": "CTAGGTAAGAGATTACGCC...",
    "Rosalind_4212": "ACTATAAGCCGTAGACTTG..."
}"""

# Find the sequence with the highest GC content
max_id = None
max_gc = 0.0

"""Initializes two variables to keep track of the sequence with the highest GC percentage.
max_id will store the sequence label (e.g., "Rosalind_8859").
max_gc will store the highest GC% value found so far (starts at 0)."""

for seq_id, dna_seq in fasta_dict.items():
    gc = gc_content(dna_seq)
    if gc > max_gc:
        max_gc = gc
        max_id = seq_id

"""Loops through each key-value pair in the FASTA dictionary.
1st code line: seq_id = the FASTA header (ID).
                dna_seq = the nucleotide sequence string.

2nd code line: Calls gc_content() function to calculate the percentage of G and C bases in that DNA sequence.

                **Formula: GC% = [(G+C) / total bases] x 100**
                Returns a floating-point number like 61.144578.

3rd code line: Compares the current GC% with the highest found so far. 
                If it's higher than anything seen before, it's the new maximum.
                If no, leave max_gc and max_id as they are.

4th code line: Stores the new highest GC%
                max_gc always contains the largest GC content encountered up to this point in the loop.

5th code line: Stores the ID of the sequence that has this new maximum GC%.
                Ensures that at the end, max_id shows which sequence has the highest GC content.

The loop checks every sequence in the FASTA-formatted data.
By always updating only when a higher GC% is found, after the loop finishes, max_gc is the largest GC content, and max_id is the ID of that sequence.         
"""

# Print final answer
print(max_id)
print(f"{max_gc:.6f}")

"""Output: 
Rosalind_8044
54.874042
"""