"""
Rosalind Problem: GRPH - A Brief Introduction to Graph Theory
Problem URL: http://rosalind.info/problems/grph/
Location: Bioinformatics Stronghold
Author: Bunsree Patel
Date: November 8, 2025
"""


"""
'graph'
'nodes'
'edges'

'incident'
'adjacent'
'degree'
'walk'
'path'
'path length'
'cycle'
'distance'
'graph theory'

'adjacency list'
'directed graph'
'directed edges'
'tail'
'head'
'overlap graph'
'suffix'
'prefix'
"""

"""Sample Dataset Problem
A graph whose nodes have all been labeled can be represented by an adjacency list, in which each row of the list contains the two node labels corresponding to a unique edge.

A directed graph (or digraph) is a graph containing directed edges, each of which has an orientation. 
That is, a directed edge is represented by an arrow instead of a line segment; the starting and ending nodes of an edge form its tail and head, respectively. 
The directed edge with tail v and head w is represented by (v,w) (but not by (w,v)). 
A directed loop is a directed edge of the form (v,v).

For a collection of strings and a positive integer k, the overlap graph for the strings is a directed graph Ok in which each string is represented by a node, 
and string s is connected to string t with a directed edge when there is a length k suffix of s that matches a length k prefix of t, as long as s≠t;
we demand s≠t to prevent directed loops in the overlap graph (although directed cycles may be present).

    Given: A collection of DNA strings in FASTA format having total length at most 10 kbp.
    Return: The adjacency list corresponding to O3. You may return edges in any order."""

from DNAToolkit import prefix, suffix, validateDNASeq,parse_fasta

# Build the overlap graph for a collection of sequences
def build_overlap_graph(fasta_dict, k):
    """
    Args:
        fasta_dict (dict): dictionary mapping sequence IDs to DNA sequences
                            parsed from a FASTA string like fasta_text
        k (int): length of overlap to check

    Returns:
        list of tuples: (seq_id1, seq_id2) where suffix of seq1 matches prefix of seq2
    """
    # Validate all sequences first
    validated_dna_dict = {}
    for seq_id, seq in fasta_dict.items():
        validated_seq = validateDNASeq(seq)
        if validated_seq:
            validated_dna_dict[seq_id] = validated_seq
        else:
            print(f"Warning: Invalid sequence for {seq_id}, skipping")
       
    # Initialize list to store edges of the overlap graph
    edges = []      

    # Compare each sequence with every other sequence
    for id1, seq1 in fasta_dict.items():
        for id2, seq2 in fasta_dict.items():
            # Ensure loop is not created (create edges only between different seqences)
            if id1 != id2:     
                # If the suffix of seq1 matches the prefix of seq 2, add an edge
                if suffix(seq1, k) == prefix(seq2, k):
                    edges.append((id1, id2))
    # Return all edges in the overlap graph
    return edges

# Input Sample Data
fasta_text = """
>Rosalind_0498
AAATAAA
>Rosalind_2391
AAATTTT
>Rosalind_2323
TTTTCCC
>Rosalind_0442
AAATCCC
>Rosalind_5013
GGGTGGG"""

# Parse the FASTA format text into a dictionary
fasta_dict = parse_fasta(fasta_text)

# Build the overlap graph with k=3
overlap_edges = build_overlap_graph(fasta_dict, 3)

# Print the adjacency list
for edge in overlap_edges:
    print(f"{edge[0]} {edge[1]}")

"""Output:
Rosalind_0498 Rosalind_2391
Rosalind_0498 Rosalind_0442
Rosalind_2391 Rosalind_2323
"""


"""Actual Dataset Problem"""
# Input Sample Data
fasta_text = """
>Rosalind_8620
GAATGTTGAGGAAGCGAAACTTTCCAAGTTCCGTCATAGCCCATCATGACGGAATTTTGG
ACGAAGCATAGTGACCGTGATTCACGC
>Rosalind_0155
GTCAACGTGGCTATCTCAATGATATTGTCAGAGGGATACATGCCACGGAAACTGAAGTTC
GCCTTAATTGTTGGGTTTTGCAACCGCGTATACGGGATCG
>Rosalind_2217
AGATGCCACGCCCGAGTGGAGCTCCAGGACTTTAAGCGGTCGTCGATGTATTATAGTGGA
GTGCGCACTACAACCGCGGATGACCCCGCTAGA
>Rosalind_7601
AGTGTGTCTACTCACCGACCGATCTGGTGACGTTCCTCCGAATTAATTTCGACTGGGGTG
TGTCTTGAATCGTGCTCCCGAGA
>Rosalind_5523
ATCTCAACCGTTACCTGGGGAAACGGTGCATAGGGCGTACCATCGGAAGCGGAACGAGAA
AAAGATTGATCACTTAAGATTCAGATGGCCCCCGGA
>Rosalind_9911
TTAAGTTCGAAGGGCGCAGTATGGTACAGGCGAGACGGGTTCGAACTTACTCCGACGGGG
ATCGGAGACAGCCGTGGGCACCCGAACCTCCACGAATTAT
>Rosalind_9836
GATTGACCAAAGTGCTGATGAACTACCCTTAAGATACAGACGGGTAGGAAAGCAATTGCA
TATGCGTATCAATGGGTCAG
>Rosalind_7250
GCCAGGTGGCAGATCGTTGCATTCTCCCCACATAAGGACACTTCTTCGAGACATTGTAAC
ATCATAGGGGTGGTCTCAGCAAATTAAGAATTGATT
>Rosalind_7230
ATCACTTTGGGCTTCGCTCGGCAACGGATTCGCCTTAGCCTTCATGTAAGGCCTTGCTTC
ACAGAGGGACAGCTCCGATTGTCACCCAA
>Rosalind_7665
TTCGTGGACAGCGTTAAATGCCCCCAATCAAACATCAGCAGCGACCGAGTGATCCATCCT
TGCACGCAACTGGTCACGGG
>Rosalind_2990
GTCTAGCGCTGTCCTCACGGGGGAGTTGCAATGTTCATTTGCCTGACCCTCCCATTTACT
CAGAGCCGTGTTGCCACTTTCCCACTTTGCTTCTCGCAG
>Rosalind_7285
ACTCCCACATATGTACGCTGTCCAGCAGAGACGAGCTAGCCGCTAACCACCATCATTCAC
GCCCCACGGCTCCCCGGATGTCCTATAGTTTC
>Rosalind_2929
CTATCCCTCTAAGCCCCTCCTCGCCAGTAGGAACTGGCTGATAGGTGCTATGTTTAGTGC
AGAAGCGGCACCAGTGAGATGCGAACATCTATTTGGGAAG
>Rosalind_6287
AGGAATTGTGCGATAAGAAGAGTTATACGGGGGTAGGGTTAGCTCCTCATCGATTCATGC
TGTTGAGATAAAAGCGCCCCATAAAGTCTCTTGAGCCCTC
>Rosalind_7294
TTATCGGATCCTGAAATTGCACCCTAGAGCTGCATACAGTCATCGCCAGCCGTAGTCAAG
TAGGAAATACTATTGGACATGACCG
>Rosalind_5715
ACTCTTAGCACCCATTAACTGATTAACGTTATTTTAGAACACGCATTATTACGCCCCTCT
CTTGGACCACCGCGAGGGGGGCTCCTTCCG
>Rosalind_3218
AAAGCGTTCGATAACTAGAGAAGTGGTTCCAAGATCCTAAGTCGCTCCGACTGGGAATCC
CCACGACCAGGGCCCTTCACAAATAGGCGCGCTAAGC
>Rosalind_5985
CAACAACCTTTTGGCGGATCCATTGGGTTTATTCGATGAACCAGGACTTTAACCTAAACA
ACGGTCTAAGTGTTCGCCTGATGCTAG
>Rosalind_4273
GACGAACTATCCGTTTAAGCCCAATGTTAACACTTTCCCATTCCGCGCCCATTCGTCGGA
GTCGATAAGAGTCAATATAGGGT
>Rosalind_3242
CCGGTTTAAGATTAGCTTCGTCTTGTAGCTAATCAGCTGCCTACATCATAGTGCGGTGCT
CGTCAGACCCTAAGCTGCTCACGTC
>Rosalind_3786
TAGATTACGCCCTTGGGATCACACACTATATGTGTTCATTGGTCCAGCCGGGGTGGCCTC
TCACTTGGAGCCATAACTTCTGCTTCACTTC
>Rosalind_3901
GAGTGTACATCACTTTACGCCGCCGAGATATAGTGACTGGCACAACGGTTAGGGTCCCAG
TTTCAGGAGGTACCGACGCGGAACGAGATTAAGG
>Rosalind_2395
TCCGCTAGAGCGCCACAAATTCTACACTGAAAAGGGGTTTTGCGTAGTTATTCAGACTAG
AACTTTACCAGGAGGAGGCATACTTGTAA
>Rosalind_5373
AGGGACTTCAATGGCTCCGGCAGAATCCATCACTTACTGGACCGGTCTCGATTGTGTCAG
GTTTCGTCAGACACACCTCCA
>Rosalind_7759
GTCTTTGTACGTCGATCTTGTTCGTGGTTACAGCCCAAGAGACAAAGAACTCTCTAGTGA
GCCAACAGAGGGGGGCCTAATGAAACAACGTACGA
>Rosalind_3618
GTCTATACCCGCAAGCCGGGGCTCTATCCTGAAATAACTACTTCTAGTTTACGTATCAAC
ATTGCTGCAGGGAGCGGTTCT
>Rosalind_3284
GAATATAATGTAAGCTCAAAGCAAGGTCACCACTTGGCCTCATGCCACGTGCTCCGGCCC
TTACAACAATGCGACGACTCATTACTCTG
>Rosalind_9052
TATACTCAAACGTCAGATAGATAGGAAGCCTGTGAGAATTAGTGAACTTACCAACAACTG
ATTATATCGCTAAAGTTTGTGCGGTAGAGAT
>Rosalind_9849
CATGACCATTTGTCGTCTCTGGGCTAGTGAGACGGAATGGGGGCGACTAAGCAACGAATC
TAGGAGGGACTGCGTACGGT
>Rosalind_2783
ACGCTGACGCGTCAAAGCATTTTCGACATCAGGGATATGATTTGGGTGATCGAAAGGCAT
GGCGCTCGGCATGGTTGACCCGTCATGG
>Rosalind_4172
GCCCGAGAGCGATCTTAAGAACTATGGCGATATGCAGCCGCTAAACGTGGTGCCGCCCCA
AGCGATCAACCTACGATAAGTTCTCCGTACGTTACCGGGG
>Rosalind_7849
ACTGGTACCGTCAAATAACTCCCAAATTGAATACTCCATACTCCTTACAACGTTAGTCAG
CCTAAGGGGGGAGGGATACGAGCCGTAATGT
>Rosalind_7027
GCCCGGTCGTTACTGACCTCGCCACCACGCCTACTTACACAAGGGACTATTTACATCACC
CCAATTGTAAACCTACCGAGAATAGTTTGAGCGG
>Rosalind_8346
CATATCTACTTAATCGGATGAACGGCACCGCAAAAAACTAATGGGCTATGAGTAGCATAC
ATCGACGCGATGTTAAGTAACGCCAACTAAAA
>Rosalind_9448
GGTCGAGTGGTGATAAGAATAGATAGCAATGGCTAGCGTGACCGCTGCCGGCGGGCCCTG
TATGTGTCCTCAAGTCAGGTGTTGGTCGG
>Rosalind_6871
CTAGCGCGGCTAATTGTCGCAGGGACTGCACCTTGGTAATATCTTCGGCCCGTATAGTAT
AGCGCATCTGATGTAGCTAGCAAAGAGATGA
>Rosalind_1869
ACGGCCACCTATGTCGAAGTGTGGCAAAAGTGGATGTGATACTACATTGCACAGAGTTAA
AACGGACTGTCGCTCTCTCGGCGC
>Rosalind_9673
CGATCTTCGTCTTATAACAGAGCGATTGATGCATGATGCAGCAGTATCGCCATAAGCATA
AGAATAACCCGAGAATGCGTGCGTACCGTGATCAGC
>Rosalind_6942
CTCCCACAAGCCATCTTGACTCGATTCTTACCTGCGCAGATTGAGATGAGGGCAAAGCAA
GAGTATCTTAGCACGAACTA
>Rosalind_0914
GACAGTTATAGCTCCAGTTAATACTTGTAGTCGCGATACCTACACCTGTACCCCTAATCA
ACAGTAAGGTAACCGATCGAGAATTCAGACTACGGGTT
>Rosalind_9450
TTCTAAAGCGTATCAGTATTAGGGACTGGCGTATTTTTTGGCCACGCATCCTTATGTTTC
TATTAACTACTGGCTGGAAAAACCGAACGCA
>Rosalind_9357
ATAGGCGCGGGTTCGTAGAGTCGACAAGCTTAAATAAACTTTGACAATTAGACTCTTGTC
GATATGAACTCTACTCGGACCAAGCCTCCGTTGA
>Rosalind_9133
CTTTATATAGCTACGCCAAGACCGCTGAACGTGTCGGGCACAGCCGGCAGGGCCGTTAGC
GACATAGCTTCGGCAACGCTG
>Rosalind_2587
GAATGTCGCGGAGCCGAGAAAGCATCTGACCAGCGTCCTGTGGGGATGTATTGAAATTCT
GGGATATCTCAGTACACCGTG
>Rosalind_7038
GGGCTTGTATATAGGGCGGGATCGACTAGGCAACTCGGCTGATAATCCCATGATCTACGC
CGCCGCAACCATAACGAAAGGTCTAATAAGGATCCGA
>Rosalind_9884
GTGTCGACTTCGCTACGGCGGTCAAGCCTGGACTAAAGATCTCAACGTAATGAAGGGCGT
CTCTGAGGTTTCTACGCAGCT
>Rosalind_0799
ACACTGGCGATTTTAAGCATCTCATCGGGAGCTGTCCGAGGCCCTAACTCTAGCGATGAA
TAGGTATGGGAAGGCTTTCCCT
>Rosalind_9386
TCGTCTTCTCCTTTTCTACCGATTCCGGTTCGCGAGTGTTGCGGACCCTCCGTACATGTG
GACATGTACAATAGACTCATATCCAACG
>Rosalind_3367
TGCAGTCGCGTGGTCTGACGTTTTAACGGTGAGCAGCCATCCTAGAACCCCGTCTCGCTT
CATTAAGCACAGTGATATTGTACAAATAGAGT
>Rosalind_3433
TAGAGTCTGCTATTCGAAAGCTAATGTCTCCTAATACCTAAGCTCACCGAGCCAAGCGAC
TACAAACACTAGTACATGGTTACGTTAAC
>Rosalind_7985
TCTCAGCACGAGCTCCTCTGATAACACCGCAATAGGCGTGGATGAGATAGTATGGATTTG
GTCGGGGTCATACTGTCCCTAGAAA
>Rosalind_1588
GCCCCGTGTCACCAATCTGTTTCTCTTTGTGAGGGAGCCGTATGGAGCCGAGCCTATATC
CGGCGGCTGCTGCCCAGTTAC
>Rosalind_8940
AGAGAGCGGTTAGCCAGTAGTACTGCTGCTGCTAGGTGCGCTTATCTAATATCGATGATG
TTGCCCGTCACATTGCAGTAACGAAAGTGTCGGC
>Rosalind_0608
AACTTCGATCTCAATCATCTATCCTTCCTACGCAGGGAGTATAAACTTCTAATACAGTAA
AATAGCTGCCAGGACTGAACTCATATCGCGGGTAAAA
>Rosalind_0726
TAGACGTTCGGCGCCTATTCAGTGCTTGGGGTTATGTTGTCGCTTACCCAGGGCGCGTAG
GAGTACGGCTATCATGTGTA
>Rosalind_8517
AATACGCATTTGGGGTAGAGTGAATTCACAACAGATAATATGGTGAGAGATAGCTCACCC
TCTAGGCCTCTGTAGCTAGATGAGGTATCGTCCGAG
>Rosalind_1561
TTAAGAGATGATCTATGAGGTGATCCGAACCGGACCCTGCAGGCGTGTCCACTTCGTGGT
TAGGTTTGGTCGTCTACATTCATGG
>Rosalind_1099
TATACCTGCCTTGAACGGGGGAGAAAAAGCTATTGTGGAGATTCTTCTGCCCCGTCCTCT
GTACTAAAAGATTGAATGCAGTGGATCTTCAGTTTA
>Rosalind_5588
ACTAGCTGCGGAGGCTACCTATAAATACCTTCCACAGAATCAGAGGATAGATAAAGCCGC
ATTGCCTTCAGTAAATAAATAACAGGGTCGCAGTT
>Rosalind_4358
CCTGGGATCTTCGGGCGTAGCTATGCCGGGACTGCTATCAATCGATCATGAGAGAACATG
TAGGTCGGGCTAAAGGCACCGATTGCAGGACAT
>Rosalind_0110
GATCGCGGCCCCGGTCAGGTACGCTCCTAGTTCGTCACATGTGTCGCTGTAACCGTACGT
TGAACCCACCCGATGTCAAAAAATGGATAACGTTG
>Rosalind_5064
AGTCACTATCACCCGCCGCTTTGTTAGGCGGCTATAATTCCGAGTTCGGCAAATTAATCT
CTGGTCCAACAGCGGCCAAAGGTTCCTATTTTTGGCATC
>Rosalind_5332
TATAGAGGGGTAACTACTAGCCTTGGTATTGCTGAGTTCAAGTGTACACTTAGCTGGCCA
CGCGGCGAACACAATCACAACGTC
>Rosalind_4727
GGTGAGGCTGCAAATCGTAACTGTCGTCTTTACTAGATGGTAGACGTTCATTCACAAGGC
TGGTGGCAGTTGTTAAAGCTAGCCTGATCCTGCTCGA
>Rosalind_3493
TGTCCTTAGTGCGACTTGGTGCACCGGTCGATCTAAACTTAGACGGATTCAATCGGGGGC
CCCCCGCGGTCCACTCGATACG
>Rosalind_4911
GGTACATCAAAATATTAGTGCCTCCACCGCACAGCCTCACAAGATCTGTGGAGGCGGCGG
ATCCGTAGATATGAGAGTACTGTT
>Rosalind_0308
TAGTATTTTTGAAAAATTTCCGCCATGTTGCTTTCGAGACACAGATTGGCCCACTCCTCA
ACGGTGGTCGCTTTGTCCCGTCTGTCAT
>Rosalind_0715
GTGACCATGGGGTACGACGCGTTTATATTATTTTCTAGGTCGATTACTGGCGGACTGACA
GACGTAGTCGCTGCTTACAAACAAT
>Rosalind_9534
GGGTAGATTTAAATTAGGGTACGAACTTTTAGGGGACATAAGGAAAGGGGTTCTGCCATT
GAATCCGCCATACTATAGCTCTAAGGTGC
>Rosalind_8634
CGTGTCCGCAATAATGATCGCTCATCGTAGGTTATGTGAGTCTCAAAATGACACTTTGGT
TATATGGCGGATCCGCTCGCTT
>Rosalind_2995
ACTGTGGTAACAAAGAACCGTGCGAAGTATCCAGCGATAACCCTGCGTTGATCCACCAAG
ATGACTTTCAGCGTACATCCTGAG
>Rosalind_9850
AGGAATGGGATCAGGCGACGAGGACAATACGGTTACTAGACTTAGCCGGTAATGGCACTA
ATTATAGCCATTAATGCCCTGGTGACATGTATAC
>Rosalind_7101
GTTCCTGCGGAGTGCAAACGTCTCACAGGCTTAGGTTAACTAATTGACCTACCTTTCTCC
CGCATGAGAGGCTGTCAGGGGTGTCGCGTC
>Rosalind_1083
GCGTAAGGAGACAGCGCGCAAGGACCGTTGCAGATTACGCGGAGATGTGGCATCCGGCGT
GCCATATTCAGAACGATCTTACGGCAATAGAGAGTATTT
>Rosalind_1264
GTATGCCGCTAGCCAGCTGGACTCCGAAGGTGTCCATATAGTAAATGGGAAAGCGTGGGA
CCTTCATGCCCTCTATACTCAAGTAGCCACGCCA
>Rosalind_0058
GAGAATCAATTTATTCCTCCCACAGAAGTCTAGCACTTGCGGATTTTCGGTACTGCCGAT
TCGTAGTAATTGGTCTCGTCTAACAACGTTCATCA
>Rosalind_1461
CTTGTGCGAACCAGTCGATCTTGAACGATGCGTTGAGCGAGGACCCGCTATCCGCCGGCA
AGCCCTCAAACTTCATTTGTCACTGCGTTACAGTTTTAC
>Rosalind_4417
CCTTCCTAAAGTTCTATGATGCGGTCGTCATCCTTGGTGTCTATGCCGAGCGTGCTTAAC
TATTATACCAACGTAACTCGTAACTTCTGACTCATATGGA
>Rosalind_1041
GAGACCAAGGCAAGGTCGGATGTCAGCTCGAGCACAACTGTCCGCGGACAGGAGTCTCAT
AAAACCGTTTCAGAACATAATGGAGTCGGACCGCG
>Rosalind_0764
AGCCGCCAAGCATTGTCTCTGAATTAGTGGCTGATGTACAACATGTGCAGCAAGCTAGTG
GGAACTTTGTCCTTTTAGTCCGCCGTTTACTTT
>Rosalind_3911
AACAGGAGCCTGCGCATTATGCACTGGCGTAGAGTAAGACGCGCGGGGGAGGTGATAGTC
GTTCGACTTCCAGGAAAGCTAATCGTCTCG
>Rosalind_9080
CGAGGAGTTGCTATTTTGATGTCGGATCTGATCACGGTCGCGCAGGCAAGTTGACAGGGT
AAACAAAATGAAGCTCTTACTCCCC
>Rosalind_8894
GGAGGCCTTCACTGTGTTGAAGGTTAATGCGACCTTGCCTAGTCGCATTGAGGGTCCGAT
CGTTTGTGGCCCTCAGAAAACTCAGTCGGGTGTACCTT
>Rosalind_7430
CGACCTAATGGCAACCAAGGCACCCACCCCAGACGCAACACACATGATAGTTACGGCGGC
CTGCCCTTTCCCGTGCATCCACAGCAAGGTGCCTATTTCA
>Rosalind_5493
GCCTACTTTATAACTGAGTACTTGCTGAATTCTCACACTGGCAGCCTACTATATAACCAT
AGAGTACCAGAGTGGGGACCTCATTTGCTGTCTTCGCTGT
>Rosalind_7303
GATGGGTGTTGGTGATCCCTTCTAACTAGACCTCCCGTCGATGTTACAAGGCATTGGTCG
CATCCCACGTCCGCTCTACATCACACA
>Rosalind_9625
CAGCAATTAACTGAGCCCTTATGTATAATGATAAGAACACGGTCTAATGTCCCGATTTAT
ACTTCCCTACCTTTGGGCGTATCTTGAACTC
>Rosalind_7802
GGGCGCATCCAGCGGGCCTATCCGAGACCGGACAAGCTGAAGGTATACATAATATGCAGG
CTCGATCTGCAACTATTGGTGTGAG
>Rosalind_8047
ACTGGAAAGCCGAGTTCGAGGCAAGTGATGAATCACACTCAGGGAAAACACTGTTTCTCA
GGGCGCAAATTGTAGTTTAGTTGGTGAGACCCTCCCATA
>Rosalind_7919
CAGGTATGGAATCATGCCATAGGTCCTCTACGTGACGAGCACGTACGCGTGCTTTAAGTG
GATAGTCACTTTGTTATCATGTGCATTCTCGATGATAAG
>Rosalind_6413
CTCTAGGATGGTAATTATACGACGGTGAAGATGGGAATCTTGCTGTACAGATGTGGCTTC
AGACCTCTCATCTGCCTTGC
>Rosalind_0605
GACGGGATCAGCGCAATACCGCTTATTATAGGAAGGGGCGATAAGGAACCAAAGCTTTGT
GTTCCCTGACAAGGTGCATGCACACGACGAT
>Rosalind_6400
GTAACCTGACCCATCTCTCATCTGATGGCCCCACACGTCGTTAAACCTATACACGAAAGC
GACAAGAATTAACATGCCCCCCCT
>Rosalind_9614
CGAGATTCTGCTAGTCCAAGATGTTATCTGTCTTGGAAGCGACTGTGAGCCCCCAGAATC
ATATAAGACAATAGTAGTTAGCC
>Rosalind_9835
TGCAACATGTAGCACTACGATCCAATTATTACAAAAACAAGAGAACGTGTCTTCGTCGTG
ATCTCTTGCGTCAATTGAACTCGTAGTT
>Rosalind_9915
GCCAGCGGTCTCCAAACATCTTACCCCCGGAGGAGACGACCATATGGATGCCGGAAGGGT
AACTAGAAATGACAAACCAGGAAAACCCCAA
>Rosalind_8408
GGCACTCAGTAAAAGATCAGTGGCATCCCCGTCTGGGTCAACCTCTATTTTTCGGATGTC
TTCTGGCGAGTTAGGTGGGCAACAGATATTAACAT
>Rosalind_8125
TGAAGTTCGACTGTGGGCGGCCATCTACCGAAGTCGTCGACGCTGTATTGTGTTTCCGGA
TCTGCGCGAGTCGGCACCAAGCGA
>Rosalind_6469
AATGGGAATCCCACCGATCCGGTATATAAAGCCGTGCAGATGAAGTCACAATGGTGAAGT
TGGACTATCGTGTAAGTGCCCACAATCGTGCATGGTACAG
>Rosalind_1220
GCGGAAGACTACAGGTAGTTCCGGCTAATATCTACGGTTGTTACACCTTCTCCTGTCACC
GTTAGATGTATTACCTCGGACAGCTGGACAGATCC"""

fasta_dict = parse_fasta(fasta_text)
overlap_edges = build_overlap_graph(fasta_dict, 3)
for edge in overlap_edges:
    print(f"{edge[0]} {edge[1]}")

"""Output:
Rosalind_0155 Rosalind_9386
Rosalind_2217 Rosalind_8940
Rosalind_7601 Rosalind_2217
Rosalind_7601 Rosalind_8940
Rosalind_5523 Rosalind_8894
Rosalind_9911 Rosalind_9052
Rosalind_9911 Rosalind_1099
Rosalind_9911 Rosalind_5332
Rosalind_9836 Rosalind_9625
Rosalind_9836 Rosalind_7919
Rosalind_7230 Rosalind_5985
Rosalind_7665 Rosalind_7038
Rosalind_7665 Rosalind_9534
Rosalind_7665 Rosalind_7802
Rosalind_2990 Rosalind_9625
Rosalind_2990 Rosalind_7919
Rosalind_7285 Rosalind_7665
Rosalind_7285 Rosalind_9450
Rosalind_6287 Rosalind_6942
Rosalind_6287 Rosalind_6413
Rosalind_7294 Rosalind_3242
Rosalind_5715 Rosalind_3242
Rosalind_3218 Rosalind_0764
Rosalind_5985 Rosalind_3786
Rosalind_5985 Rosalind_3433
Rosalind_5985 Rosalind_0726
Rosalind_5985 Rosalind_0308
Rosalind_4273 Rosalind_9448
Rosalind_4273 Rosalind_4727
Rosalind_4273 Rosalind_4911
Rosalind_3242 Rosalind_0155
Rosalind_3242 Rosalind_2990
Rosalind_3242 Rosalind_7759
Rosalind_3242 Rosalind_3618
Rosalind_3786 Rosalind_7665
Rosalind_3786 Rosalind_9450
Rosalind_3901 Rosalind_6287
Rosalind_3901 Rosalind_5373
Rosalind_3901 Rosalind_9850
Rosalind_7759 Rosalind_9673
Rosalind_7759 Rosalind_9080
Rosalind_7759 Rosalind_7430
Rosalind_7759 Rosalind_9614
Rosalind_3618 Rosalind_7985
Rosalind_9052 Rosalind_9836
Rosalind_9052 Rosalind_0110
Rosalind_9052 Rosalind_7303
Rosalind_9849 Rosalind_9448
Rosalind_9849 Rosalind_4727
Rosalind_9849 Rosalind_4911
Rosalind_4172 Rosalind_7038
Rosalind_4172 Rosalind_9534
Rosalind_4172 Rosalind_7802
Rosalind_7849 Rosalind_3493
Rosalind_8346 Rosalind_3218
Rosalind_6871 Rosalind_8125
Rosalind_9673 Rosalind_0764
Rosalind_6942 Rosalind_2929
Rosalind_6942 Rosalind_6871
Rosalind_0914 Rosalind_7101
Rosalind_9357 Rosalind_8125
Rosalind_2587 Rosalind_9884
Rosalind_2587 Rosalind_0715
Rosalind_7038 Rosalind_9673
Rosalind_7038 Rosalind_9080
Rosalind_7038 Rosalind_7430
Rosalind_7038 Rosalind_9614
Rosalind_0799 Rosalind_4358
Rosalind_0799 Rosalind_4417
Rosalind_9386 Rosalind_2783
Rosalind_9386 Rosalind_1869
Rosalind_3367 Rosalind_7601
Rosalind_3367 Rosalind_5064
Rosalind_3433 Rosalind_0608
Rosalind_3433 Rosalind_3911
Rosalind_7985 Rosalind_3218
Rosalind_8940 Rosalind_8408
Rosalind_0608 Rosalind_3218
Rosalind_0726 Rosalind_1264
Rosalind_0726 Rosalind_6400
Rosalind_8517 Rosalind_3901
Rosalind_8517 Rosalind_0058
Rosalind_8517 Rosalind_1041
Rosalind_1099 Rosalind_9911
Rosalind_1099 Rosalind_7294
Rosalind_1099 Rosalind_1561
Rosalind_5588 Rosalind_7101
Rosalind_4358 Rosalind_9849
Rosalind_4358 Rosalind_8346
Rosalind_5064 Rosalind_5523
Rosalind_5064 Rosalind_7230
Rosalind_5332 Rosalind_0155
Rosalind_5332 Rosalind_2990
Rosalind_5332 Rosalind_7759
Rosalind_5332 Rosalind_3618
Rosalind_4727 Rosalind_9673
Rosalind_4727 Rosalind_9080
Rosalind_4727 Rosalind_7430
Rosalind_4727 Rosalind_9614
Rosalind_3493 Rosalind_2783
Rosalind_3493 Rosalind_1869
Rosalind_4911 Rosalind_7101
Rosalind_0308 Rosalind_9849
Rosalind_0308 Rosalind_8346
Rosalind_0715 Rosalind_8517
Rosalind_0715 Rosalind_6469
Rosalind_9534 Rosalind_3367
Rosalind_9534 Rosalind_9835
Rosalind_8634 Rosalind_9133
Rosalind_8634 Rosalind_1461
Rosalind_2995 Rosalind_3901
Rosalind_2995 Rosalind_0058
Rosalind_2995 Rosalind_1041
Rosalind_7101 Rosalind_0155
Rosalind_7101 Rosalind_2990
Rosalind_7101 Rosalind_7759
Rosalind_7101 Rosalind_3618
Rosalind_4417 Rosalind_8894
Rosalind_1041 Rosalind_1083
Rosalind_1041 Rosalind_1220
Rosalind_3911 Rosalind_9386
Rosalind_8894 Rosalind_9133
Rosalind_8894 Rosalind_1461
Rosalind_5493 Rosalind_3493
Rosalind_7303 Rosalind_0799
Rosalind_9625 Rosalind_6942
Rosalind_9625 Rosalind_6413
Rosalind_7802 Rosalind_3901
Rosalind_7802 Rosalind_0058
Rosalind_7802 Rosalind_1041
Rosalind_8047 Rosalind_9357
Rosalind_6413 Rosalind_3367
Rosalind_6413 Rosalind_9835
Rosalind_0605 Rosalind_9836
Rosalind_0605 Rosalind_0110
Rosalind_0605 Rosalind_7303
Rosalind_6400 Rosalind_4358
Rosalind_6400 Rosalind_4417
Rosalind_9614 Rosalind_7250
Rosalind_9614 Rosalind_4172
Rosalind_9614 Rosalind_7027
Rosalind_9614 Rosalind_1588
Rosalind_9614 Rosalind_5493
Rosalind_9614 Rosalind_9915
Rosalind_9835 Rosalind_7101
Rosalind_9915 Rosalind_5985
Rosalind_8408 Rosalind_9849
Rosalind_8408 Rosalind_8346
Rosalind_8125 Rosalind_9673
Rosalind_8125 Rosalind_9080
Rosalind_8125 Rosalind_7430
Rosalind_8125 Rosalind_9614
Rosalind_6469 Rosalind_9625
Rosalind_6469 Rosalind_7919
Rosalind_1220 Rosalind_2395
"""
