"""
Rosalind Problem: SPLC - RNA Splicing
Problem URL: http://rosalind.info/problems/splc/
Location: Bioinformatics Stronghold
Author: Bunsree Patel
Date: November 11, 2025
"""

"""
'RNA polymerase' (RNAP) - breaks the bonds joining complementary bases of DNA
'complementary bases'
'precursor mRNA' (pre-mRNA)
'template strand'
'coding strand'
replacement of Thymine with Uracil by RNAP
'double helix'

'introns'
'exons'
'splicing'
'spliceosome'
exons from a gene are known as gene's 'coding region'
"""

"""Sample Dataset Problem
After identifying the exons and introns of an RNA string, 
we only need to delete the introns and concatenate the exons to form a new string ready for translation.

    Given: A DNA string s (of length at most 1 kbp) and a collection of substrings of s acting as introns. All strings are given in FASTA format.
    Return: A protein string resulting from transcribing and translating the exons of s. 
    (Note: Only one solution will exist for the dataset provided.)
"""

from DNAToolkit import solve_splc, parse_fasta

fasta_text = """
>Rosalind_10
ATGGTCTACATAGCTGACAAACAGCACGTAGCAATCGGTCGAATCTCGAGAGGCATATGGTCACATGATCGGTCGAGCGTGTTTCAAAGTTTGCGCCTAG
>Rosalind_12
ATCGGTCGAA
>Rosalind_15
ATCGGTCGAGCGTGT
"""
# In FASTA format, the first sequence is always the main gene, and all subsequent sequences are the introns to remove.
# In real genes: You start with the full gene (exons + introns mixed together)

sequences = parse_fasta(fasta_text)

# Call function and store result
protein = solve_splc(fasta_text)

# Print the result
print(protein)
"""Output:
MVYIADKQHVASREAYGHMFKVCA"""

"""Actual Dataset Problem"""

fasta_text = """
>Rosalind_9041
ATGAGCCCATGCTGGGTGAATCGTGACTTCCGGTCTCAAAAGCATCGCTGTACACCGACG
ATGGTTTAATCCGCACTTGCATATCGGTCGTGTCAGCTCTGATAAGCTAGGAGATCGCAG
GGCCGTGAGTAATGGCTGCTCAATCTAGAAATCTAGTGCCTGGATCTCAGGAGCAGTCCA
TCAAGTCCTTTCCTTAAGTTATTAACTGCGAGGTCACATATCGTATAACAAGCTCTCACA
TATTATGAACGAAAGTAGTGAGCTTCTATATGCGGGTTTTTAAGCAAAATTAACTATCCA
ACAACCCATCTTCATTCCCAGGTCTACTTTGTATTACGGCATTTCGGTATCGCCGTTGTT
CAATGAGCGTCAGTATTCTAGGCGTGGAAGTATCCCTAAGATACCACATAGTAGACAGTA
TTATTCCTACTGCGGAGTCGGTACGTTCTATATGAGCCACGTGATTCTCCTGATCCGCCG
GTCGTTCTCTTGTGAAGGTTACGGGCTTTTGAAGAAGCGTTCGCTGCAAGTAGTTGTCCA
ATAGGGTGTCGCTCTACCTGAGTTGACCGTCTCCTTCAAAACAGTGTTGGGAGTTTCTAC
TGCTCCTGTCAGGGTGGACGAGCGCGGAAAAAATATAAGTGAAGATCAGTTAGCATTTTT
TGTCTCATACTGAACTTGGGAGTGGGACTTCTGCGATGCTGCGATGCGACCCAGACGCTG
TGTAGTTCTCACCTCATCGACGCTGGAGGCAGACGCACCATAGTGCGCGGTACTCGGGCC
CGCTAGTCACTTCCCTGATAGTCGCGTTACTTCCATGACGTTGTTGCTTCATCGATCTGA
GCTCTGGTTCGATCCTTGCTGGAAATATGAGGGTGCTATTCTTACTTTAATTGTCCGCGG
GCTGTCACTCATGTTAGGTGAGACGGGGACAATTACATTTTTCGCACGGCCTGTTCGTAG
TACTGACCAATTACCACTATACAAAATATTTAG
>Rosalind_0052
GTTTAATCCGCACTTGCATATCGGTCGTGTCAGCTCTGATAAG
>Rosalind_4004
TGTCGCTCTACCTGAGTTGACCGTCTCCTTCAAAA
>Rosalind_3031
TGAGACGGGGACAATTACATTTTTCGCACGGCCTGTTCGTAGTACTGA
>Rosalind_5074
CATCTTCATTCCCAGGTCTACTTTGTATTACGGCATTTCGGTATCGC
>Rosalind_9744
GCGTTACTTCCATGACGTTGT
>Rosalind_3862
AGATACCACATAGTAGACAGTATTATTCCTACTGCGGAGTCGGTACGTTC
>Rosalind_6023
TTAAGTTATTAAC
>Rosalind_4298
ATATTATGAACGAAAGTAGTGAGCTTCTATATGCGGGTTTTTAAGC
>Rosalind_3693
TTCTCTTGTGAAGGTTACGGGCTTTTGAAGAA
>Rosalind_7385
ATCTAGAAATCTAGTGCCTGGATCTCAGGAGCA
>Rosalind_5563
ATGCTGCGATGCGACCCAGACGCTGTGTAGTTCTCACCTCATCGACGC
>Rosalind_1703
TAAGTGAAGATCAGTTAGCATTTTTTGTCT
>Rosalind_1944
GCTGGAAATATGAGGGTGCTATTCTTACTTT
"""

sequences = parse_fasta(fasta_text)
protein = solve_splc(fasta_text)
print(protein)
"""Output:
MSPCWVNRDFRSQKHRCTPTMLGDRRAVSNGCSVHQVLSCEVTYRITSSHKINYPTTRCSMSVSILGVEVSLYMSHVILLIRRSAFAASSCPIGQCWEFLLLLSGWTSAEKIHTELGSGTSAWRQTHHSARYSGPLVTSLIVCFIDLSSGSILNCPRAVTHVRPITTIQNI"""

