"""
Rosalind Problem: TRAN - Transitions and Transversions
Problem URL: http://rosalind.info/problems/tran/
Location: Bioinformatics Stronghold
Author: Bunsree Patel
Date: November 11, 2025
"""

"""
'purine' - 'A', 'G'
'pyrimidine' - 'C', 'T'
'transitions' - substitutes one 'purine' for another - "A ↔ G" and one 'pyrimidine' for another - "C ↔ T"
'transversions' - interchange of a purine for a pyrimidine base, or vice-versa
    - require a more drastic change to the base's chemical structure
    - across the entire genome, the ratio of transitions to transversions is on average about 2.
        - in coding regions, transitions:transversions ratio is typically higher (often exceeding 3)
            - ***GIVE REASONING DUE TO transition in coding regions being less likely to change the encoded amino acid; particularly when the substituted base is the third member of a codon**
            - this kind of substitution, that does not affect organism's protein makeup is known as a 'silent substitution'
            - ratio provides a quick and useful statistic for potentially identifying coding DNA.
"""

"""Sample Dataset Problem
For DNA strings s₁ and s₂ having the same length, their transition/transversion ratio R(s₁,s₂) is the ratio of the total number of transitions to the total number of transversions, 
where symbol substitutions are inferred from mismatched corresponding symbols as when calculating Hamming distance (see “Counting Point Mutations”).
    
    Given: Two DNA strings s₁ and s₂ of equal length (at most 1 kbp).
    Return: Return the transition/transversion ration R(s₁,s₂)."""

from DNAToolkit import parse_fasta, transition_transversion_ratio

fasta_text = """
>Rosalind_0209
GCAACGCACAACGAAAACCCTTAGGGACTGGATTATTTCGTGATCGTTGTAGTTATTGGA
AGTACGGGCATCAACCCAGTT
>Rosalind_2200
TTATCTGACAAAGAAAGCCGTCAACGGCTGGATAATTTCGCGATCGTGCTGGTTACTGGC
GGTACGAGTGTTCCTTTGGGT
"""

ratio = transition_transversion_ratio(fasta_text)
print(round(ratio, 11))
"""Output:
1.21428571429"""

"""Actual Dataset Problem"""

fasta_text = """
>Rosalind_4818
CCACCGAAGGTGCCTCCGAAGAGGGCATTCCCCTATCTGTTTAGACATTAACTGCGACCT
CCATTCATTAACAACAATCTGGTACTACTATGTCCACGTTTAGTTTATTTCTCGCGTCGA
CAGCCACTTCAGCACTACCCTTCTTAGCTATGGAAAACTTCCATGGTGTTCTGGCGGACA
TACGCGTAGGACACGCCGCCACCTACTGGCTGCCCGGTGCGGTGGACGCTCATGCCGGTC
ATCACCCCACTCCACCCTTGATTTGACCGTCATGTCTAGGCGAAAATGGATAAAGCCTGG
CTGAGCTGAGCTGTCATATAGTATACTAAGAGTAACAGTATTAAAAAACCCAGGGCCCAG
TAAAAGGTCAATAGGATTCATAGCTGCTAATATGCCGTAAACATTAGTAGGGATAGGTAA
AGTTGCGAAAGCTGTGGTACCTCCACCTGTAGAAATACTACAGGGCACTGTTCCTGGGCG
ATTGCTTCTATACCTTTCACAAGGTCACCGTCTAAGGACCGTGATTGGCCCTTATCGCAG
TCGGCTAGGGGTTTCTATCGCTCCCGACGCAAGATAGGTTCTTTGATCAGCGGCGAGCGC
TTCGGTAGTTATTTAAGCCGCTGTCTTTTACGTGTGCGTTCGACGTGCGACCATTCTGCT
TTTGGGAGCTGTATGGCCCGTAGTGAAGGGATTATGGAAACCGCCAAGACAATCGGCTTC
CGAGTAACTGAGACCGCAATCTCGAGTACGTTCGCACCATCAGCGCGCCCACATCACATG
GATAAGCCCTTTCCCGGTTAGCCTGCGTCCATTCGGAACCATGGTGGGTCGCTAACAAGT
AAATCCGGGCGCGG
>Rosalind_5308
TCATCGAAAGTGCCTGCGAATAGGGCACTTCCCTAGCGGAATAGCCATGAGCTGCGGCCT
CCTTATACTAACAAGGATCTGGTACTACTATCTGTACGTGTAGTTTGTTGCTCACATCTA
CAACCACTTCAGCGTTACTTTTCCTAACTGTAGAATATTTCTACGGTGATCTGGCGGACT
TACGCGTAGGACCCGCCGCCACCTACTGCCTATCGGGTGCAGCAAGCACTCATATGGTTC
ATCGTCATACTTCGCCTTTGATCTGCACGGCATATCTAGGCAAAATTCGATAAAGCCAGG
CCAGGGCAAGCTGTGAGATAGCTTGTTAAGAATGTCATCGCCAACGAACTCAGGGCTCAG
TAAATGCTCTATAGTATTCATAGCTGCCAGCATGCCGTAAACATTAGCAGGAGCAGGTAA
GGTTGCGAAGGTTAGAGTACTTCGACTTGGAGAAACGCTCACGGGCCATGTCATTGGGGG
ATTGCTTCTGCATCCCCCGCAAGGACAGCGTCTCAACCTCGAGGTTGGCCATCAACGGGG
TCAGCTTGATGTGTCTGTTACTTCCGAAATAAAGTGGACTCATTGACCAGTGGTGAGCAC
GTGGGGAGTTATCTAGGCCGCCATCCTTTACGTGTGCATTCTTCGTACGACCATTTTGCC
TTTGGGAACTGGGTGGTCCGTAGTGAAGGAAGCACGGTATCCGTCAAACCAACTGGCTTC
CGAGTAACTGAGACCGCAGTTTAGAATGTTACCGCAGCCCCACCGCGCCGACATAAAATA
GATAGGCTCCTGCCTCGTCAGTATGTGTTCATCTATGACCATAACAGGTCGCTAACAACT
AGGCCTAGCCCTGT
"""

ratio = transition_transversion_ratio(fasta_text)
print(round(ratio, 11))
"""Output:
1.69892473118"""