"""
Rosalind Problem: FRMT - Data Formats
Problem URL: http://rosalind.info/problems/frmt/
Location: Bioinformatics Armory
Author: Bunsree Patel
Date: November 28, 2025
"""

"""
# Popular Data Formats:
- FASTA (.fas, .fasta)
- NEXUS (.nex, .nexus, .nxs)
- PHYLIP "Phylogeny Interference Package" (.phy)

# FASTA
- string is introduced by a line that begins with '>', followed by string label i.e. Rosalind_2496
- the next line that begins with '>' completes the current string and initiates next string label

# GenBank https://www.ncbi.nlm.nih.gov/genbank/
- world's largest genetic database, hosted by NCBI
- contains an annotated collection of all publicly available nuc strings and their protein translations.
- constantly updated from individual labs and large-scale sequencing centers
- Example for a Protein:
    Accession: 'A2Z669'
- Note: 'Send to:' drop-down at the top right of the page for exporting an entry to a variety of file formats
"""

"""Sample Dataset Problem

GenBank can be accessed at link above.
A detailed description of the GenBank format can be found here.
A tool, from the SMS 2 package, for converting GenBank to FASTA can be found at https://www.bioinformatics.org/sms2/genbank_fasta.html.
    Given: A collection of n (n≤10) GenBank entry IDs.

    Return: The shortest of the strings associated with the IDs in FASTA format."""

# Use Bio.Entrez module from GBK problem
from Bio import Entrez
Entrez.email = "bunsree@gmail.com"
handle = Entrez.efetch(db="nucleotide", id=["FJ817486, JX069768, JX469983"], rettype="fasta")
records = handle.read()
print(records)

"""Output:
>FJ817486.1 Malus hybrid cultivar flavanone 3-hydroxylase protein (F3H) mRNA, complete cds
CGCGTATTTCGTTTGAGCCAATACCAAGTAGACAGAACCAACAAATTCGACACCAAATATGGCTCCTGCT
ACTACGCTCACATCCATAGCGCATGAGAAAACCCTGCAACAAAAATTTGTCCGAGACGAAGACGAGCGTC
CAAAGGTTGCCTACAACGACTTCAGCAACGAAATTCCGATCATCTCGCTTGCCGGGATCGATGAGGTGGA
AGGCCGCCGGGGCGAGATTTGCAAGAAGATTGTAGCGGCTTGTGAAGACTGGGGTATTTTCCAGATTGTT      
GACCATGGGGTTGATGCTGAGCTCATATCGGAAATGACCGGTCTCGCTAGAGAGTTCTTTGCTTTGCCAT      
CGGAGGAGAAGCTCCGCTTCGACATGTCCGGTGGCAAAAAGGGTGGCTTCATCGTGTCCAGTCATTTACA      
GGGAGAAGCTGTGCAAGATTGGCGTGAAATTGTGACCTACTTTTCATATCCGATTCGTCACCGGGACTAT      
TCGAGGTGGCCAGACAAGCCTGAGGCCTGGAGGGAGGTGACAAAGAAGTACAGTGACGAGTTGATGGGGC      
TGGCATGCAAGCTCTTGGGCGTTTTATCAGAAGCCATGGGGTTGGATACAGAGGCATTGACAAAGGCATG      
TGTGGACATGGACCAAAAAGTCGTCGTGAATTTCTACCCAAAATGCCCTCAGCCCGACCTAACCCTTGGC      
CTCAAGCGCCATACCGACCCGGGCACAATTACCCTTCTGCTTCAAGACCAAGTTGGGGGCCTCCAGGCTA      
CTCGGGATGATGGGAAAACGTGGATCACCGTTCAACCAGTGGAAGGAGCTTTTGTGGTCAATCTTGGAGA      
TCATGGTCATCTTCTGAGCAATGGGAGGTTCAAGAATGCTGATCACCAAGCAGTGGTGAACTCAAACAGC      
AGCAGGCTGTCCATAGCCACATTCCAGAACCCAGCGCAAGAAGCAATAGTGTATCCACTCAGTGTGAGGG      
AGGGAGAGAAGCCGATTCTCGAGGCGCCAATCACCTACACCGAGATGTACAAGAAGAAGATGAGCAAGGA      
TCTTGAGCTCGCCAGGCTGAAAAAACTGGCCAAGGAACAGCAATCGCAGGACTTGGAGAAAGCCAAAGTG      
GATACAAAGCCAGTGGACGACATTTTTGCTTAGACTTTTCCAGTCACTTGAAAGCTCTTTGTGGAACTAT      
AGCTACTTGTACCTTTTCCTTCCACTTCTTGTACTCGTAACTTCTTTTTGGTGTGCTGGTGGCTTCCCCC      
CTAATCTGTTTAAGATCCGTGGTTGTCAAGGGCCCTTATATCCCATATTTAGTTTTTGTTCTTGAATTTT      
CATATCAGTTTCTTATCCTCCAACTTAAAAAAAAAAAAAA

>JX069768.1 Momordica charantia carotenoid cleavage dioxygenase 1 (CCD1) mRNA, complete cds
ATGGCGGAGGAGAAGCAGAAGCTCAATGGCGGAGTTGTTGACCGCTCGTTGGTGGAGGTCAATCCCAAGC      
CAAGCAAAGGCCTGGCTTCGAAGGCCACGGATTTGTTGGAGAAGCTGTTTGTGAAGCTCATGTATGATGC      
TTCAAACCCTCAGCATTATCTTTCCGGTAATTTCGCTCCGGTTCGCGATGAGACGCCTCCGATTACCGAT      
CTCCCTGTTAAAGGGTATCTTCCGGAATGCTTAAATGGAGAGTTTGTTAGGGTGGGACCAAATCCGAAGT      
TTAGCCCAGTTGCTGGCTATCACTGGTTTGACGGAGATGGCATGATCCATGGACTGCGCATTAAAGATGG      
AAAAGCAACATATGTTTCCCGTTATGTGAAGACATCTCGACTTAAACAAGAAGAATATTTTGGAGGTGCT      
AAATTCATGAAGATTGGTGATCTCAAAGGGTTCTTTGGGTTAATAATGGTCAATATGCAAATGCTGAGAG      
CAAAGTTGAAAGTGTTGGATGTTTCATATGGAACTGGGACAGGTAACACGGCTCTCATATATCATCATGG      
GAAGCTGCTTGCACTATCGGAGGCAGATAAACCTTATGTTATAAAAGTGTTGGAGGATGGAGACCTGCAA      
ACACTTGGTCTGCTGGATTATGACAAGAGATTAACGCACTCCTTCACTGCTCACCCAAAGGTTGACCCAG      
TGACTGGCGAAATGTTTACATTTGGTTATTCCCATTCACCACCATATGTTACTTACAGAGTTATTTCCAA      
GGATGGTCTCATGCATGACCCAATACCAATCACAATACCAAACCCGGTCATGATGCATGACTTCGCCATT      
ACTGAAAATTATGCAATTTTTATGGATCTTCCTTTATATTTTAAACCCAAGGAATTGGTCAAAGAAAATA      
AGTTAATTTTCACATTTGATGCTACTAAAAGAGCACGGTTTGGCGTGCTTCCAAGATATGCAAGAGATGA      
TTTGCTTATCCGATGGTTTGAGCTTCCAAATTGTTTTATATTTCATAATGCTAATGCCTGGGAGGAAGGA      
GATGAAGTAGTTTTGATTACTTGCCGTCTTGAGAACCCAGACTTGGACATGGTCAGTGGGTCTGTCAAGG      
AGAAGCTTGAGAACTTCTCAAATGAGCTGTATGAGATGAGATTCAATCTTAAATCTGGTCGAGCTTCACA      
GAAGAAACTATCAGAATCTGCTGTAGATTTTCCTAGAGTGAACGAAAGCTACACTGGCAGGAAACAACAA      
TATGTATATGGAACTATACTGGACAGCATTGCAAAAGTCACGGGGATTGCCAAATTTGATCTGAATGCTA      
AACCAGAAACTGGAAAAACAAAGATTGAAGTTGGAGGAAATGTTCAGGGCCTCTATGACCCCGGACCTGG      
TAGATTTGGTTCTGAAGCTATCTTTGTTCCTCGCATACCTGGCACCACTTCAGAAGAAGATGATGGCTAC      
TTAATATTCTTCGTACATGATGAGAACACCGGAAAATCGTCGGTGAATGTCATTGATGCAAAAACTATGT      
CAACTGAGCCTGTTGCAGTCGTTGAACTGCCACACAGAGTTCCATACGGGTTTCATGCCTTCTTTGTAAC      
AGAGGAGCAACTTCAAGAACAAGAAAGGCTCTGA

>JX469983.1 Zea mays subsp. mays clone UT3343 G2-like transcription factor mRNA, partial cds
ATGATGTATCATGCGAAGAATTTTTCTGTGCCCTTTGCTCCGCAGAGGGCACAGGATAATGAGCATGCAA      
GTAATATTGGAGGTATTGGTGGACCCAACATAAGCAACCCTGCTAATCCTGTAGGAAGTGGGAAACAACG      
GCTACGGTGGACATCGGATCTTCATAATCGCTTTGTGGATGCCATCGCCCAGCTTGGTGGACCAGACAGA      
GCTACACCTAAAGGGGTTCTCACTGTGATGGGTGTACCAGGGATCACAATTTATCATGTGAAGAGCCATC      
TGCAGAAGTATCGCCTTGCAAAGTATATACCCGACTCTCCTGCTGAAGGTTCCAAGGACGAAAAGAAAGA      
TTCGAGTGATTCCCTCTCGAACACGGATTCGGCACCAGGATTGCAAATCAATGAGGCACTAAAGATGCAA      
ATGGAGGTTCAGAAGCGACTACATGAGCAACTCGAGGTTCAAAGACAACTGCAACTAAGAATTGAAGCAC      
AAGGAAGATACTTGCAGATGATCATTGAGGAGCAACAAAAGCTTGGTGGATCAATTAAGGCTTCTGAGGA      
TCAGAAGCTTTCTGATTCACCTCCAAGCTTAGATGACTACCCAGAGAGCATGCAACCTTCTCCCAAGAAA      
CCAAGGATAGACGCATTATCACCAGATTCAGAGCGCGATACAACACAACCTGAATTCGAATCCCATTTGA      
TCGGTCCGTGGGATCACGGCATTGCATTCCCAGTGGAGGAGTTCAAAGCAGGCCCTGCTATGAGCAAGTC      
A
"""

from Bio import Entrez, SeqIO

Entrez.email = "bunsree@gmail.com"
# Fetch the sequence from NCBI
handle = Entrez.efetch(
    db="nucleotide",
    id=["FJ817486, JX069768, JX469983"],
    rettype="fasta",
    retmode="text"
)

# Parse the FASTA record into a list
records = list (SeqIO.parse(handle, "fasta"))

# Print each record ID
for record in records:
    print("Sequence Length:", len(record.seq))
    print(record.format("fasta"))

# Find the shortest string/sequence
shortest = min(records, key=lambda r: len(r.seq))

# Print label and the shortest sequence info in FASTA
print("\n*****Shortest sequence:******")
print("Sequence length:", len(shortest.seq))
print(shortest.format("fasta"))

"""Output:
Shortest sequence:
Sequence length: 771
>JX469983.1 Zea mays subsp. mays clone UT3343 G2-like transcription factor mRNA, partial cds
ATGATGTATCATGCGAAGAATTTTTCTGTGCCCTTTGCTCCGCAGAGGGCACAGGATAAT
GAGCATGCAAGTAATATTGGAGGTATTGGTGGACCCAACATAAGCAACCCTGCTAATCCT
GTAGGAAGTGGGAAACAACGGCTACGGTGGACATCGGATCTTCATAATCGCTTTGTGGAT
GCCATCGCCCAGCTTGGTGGACCAGACAGAGCTACACCTAAAGGGGTTCTCACTGTGATG
GGTGTACCAGGGATCACAATTTATCATGTGAAGAGCCATCTGCAGAAGTATCGCCTTGCA
AAGTATATACCCGACTCTCCTGCTGAAGGTTCCAAGGACGAAAAGAAAGATTCGAGTGAT
TCCCTCTCGAACACGGATTCGGCACCAGGATTGCAAATCAATGAGGCACTAAAGATGCAA
ATGGAGGTTCAGAAGCGACTACATGAGCAACTCGAGGTTCAAAGACAACTGCAACTAAGA
ATTGAAGCACAAGGAAGATACTTGCAGATGATCATTGAGGAGCAACAAAAGCTTGGTGGA
TCAATTAAGGCTTCTGAGGATCAGAAGCTTTCTGATTCACCTCCAAGCTTAGATGACTAC
CCAGAGAGCATGCAACCTTCTCCCAAGAAACCAAGGATAGACGCATTATCACCAGATTCA
GAGCGCGATACAACACAACCTGAATTCGAATCCCATTTGATCGGTCCGTGGGATCACGGC
ATTGCATTCCCAGTGGAGGAGTTCAAAGCAGGCCCTGCTATGAGCAAGTCA
"""

"""Actual Dataset Problem

NM_214399 NM_131329 NM_002133 FJ817486 BT149867 NM_002037 HM595636 JX308817

"""

Entrez.email = "bunsree@gmail.com"
# Fetch the sequence from NCBI
handle = Entrez.efetch(
    db="nucleotide",
    id=["NM_214399, NM_131329, NM_002133, FJ817486, BT149867, NM_002037, HM595636, JX308817"],
    rettype="fasta",
    retmode="text"
)

# Parse the FASTA record into a list
records = list (SeqIO.parse(handle, "fasta"))

# Print each record ID
for record in records:
    print("Sequence Length:", len(record.seq))
    print(record.format("fasta"))

# Find the shortest string/sequence
shortest = min(records, key=lambda r: len(r.seq))

# Print label and the shortest sequence info in FASTA
print("\n*****Shortest sequence:*****")
print("Sequence length:", len(shortest.seq))
print(shortest.format("fasta"))

"""Output:
Shortest sequence:
Sequence length: 621
>JX308817.1 Medicago papillosa FRUITFULLb mRNA, partial cds
AGGATTGAGAACAAGATCAATAGACAAGTCACTTTTTCACAGAGAAGGTCTGGTTTGTTG
AAGAAAGCACAAGAGATCTCTGTGCTTTGTGATGCTGATGTTGCTCTCATTATTTCCTCT
ACTAAAGGAAAGCTTTTTGAATACTCCAGCGATCCATGTATGGAAAAAATTCTTGAACGA
TACGAGAGATGTTCGTATATGGAAAGGCAGCTTGTTACAAGTGACCAGTCACCAAATGAA
AATTGGGTTCTAGAGCACGCAAAACTCAAGGCTAGGATGGAAGTGCTTCAGAGAAATCAA
AGGAATTTTATGGGAGAAGACTTGGATGGTTTAGGTCTCAAAGAGCTTCAAAGTTTGGAA
CAACAACTTGATTCAGCTCTCAAACAAATTAGATCACGGAAGAACCAAGTTATGTATGAA
TCTATTTCAGAACTTCAGAAAAAGGATAAGGCCCTCCAAGAACATAACAACTTGCTCGCC
AAGAAGATAAAGGAAAAAGAGAAGGAACTTGCTCAAGAGGAACTGCAAAATAGTGTGGAG
GTGACTCCAATTGAAACTCAACCATTGGAATCCATGAATACTACAGGATCTGGGTCCCCA
CATGCGAATTGCAATGAAGAA
"""