import pandas as pd
import numpy as np
import os
import glob
import re  # ✓ TRIPLE CHECKED - THIS IS HERE
from pathlib import Path

# --- Configuration ---
ROOT_DIR = Path(r"C:\Users\meeko\rosalind-bioinformatics\multispecific_antibodies")
SEQUENCE_EXCEL = ROOT_DIR / "all_antibody_sasa_chains.xlsx"
PDB_OUTPUT_DIR = ROOT_DIR / "PDB_Output_Files"
ML_PREDICTIONS_DIR = ROOT_DIR / "ML_Predictions"
FINAL_REPORT_PATH = ROOT_DIR / "Antibody_Comparison_Report_2025.xlsx"

def load_structural_sasa():
    """Scrapes all .sasa.txt files generated by the 3D Builder."""
    sasa_records = []
    print("Searching for structural SASA files...")
    
    # Recursively find all .sasa.txt files
    sasa_files = glob.glob(str(PDB_OUTPUT_DIR / "**" / "*.sasa.txt"), recursive=True)
    print(f"Found {len(sasa_files)} .sasa.txt files")
    
    for file_path in sasa_files:
        path_obj = Path(file_path)
        # Extract: zolbetuximab_Pair_1.sasa.txt -> zolbetuximab_Pair_1
        pair_id = path_obj.stem.replace(".sasa", "") 
        # Extract: zolbetuximab_Pair_1 -> zolbetuximab
        antibody_name = pair_id.split("_Pair")[0]
        
        try:
            with open(file_path, 'r') as f:
                content = f.read()
                # Look for "Total SASA: 12592.51 Å²" pattern
                sasa_match = re.search(r"Total SASA:\s*([\d.]+)", content)
                if sasa_match:
                    sasa_value = float(sasa_match.group(1))
                else:
                    # Fallback: grab first number found
                    numbers = re.findall(r"\d+\.?\d*", content)
                    if numbers:
                        sasa_value = float(numbers[0])
                    else:
                        print(f"Warning: No SASA value in {path_obj.name}")
                        continue
                
                sasa_records.append({
                    'Antibody_Name': antibody_name,
                    'Pair_ID': pair_id,
                    'Structural_SASA_Å2': sasa_value,
                    'Source_File': str(path_obj.name)
                })
                print(f"{antibody_name}: {sasa_value:.2f} Ų")
                
        except Exception as e:
            print(f"Error reading {path_obj.name}: {e}")
            
    return pd.DataFrame(sasa_records)

def load_ml_predictions():
    """Load ML-predicted SASA from ml_sasa_predictor_chains.py output."""
    print("\nSearching for ML prediction files...")
    
    ml_files = []
    
    # Search in ML_Predictions directory
    if ML_PREDICTIONS_DIR.exists():
        ml_files.extend(glob.glob(str(ML_PREDICTIONS_DIR / "*.csv")))
        ml_files.extend(glob.glob(str(ML_PREDICTIONS_DIR / "*.xlsx")))
    
    # Also check root directory for prediction files
    ml_files.extend(glob.glob(str(ROOT_DIR / "*prediction*.csv")))
    ml_files.extend(glob.glob(str(ROOT_DIR / "*ml_sasa*.csv")))
    
    print(f"Found {len(ml_files)} potential ML files")
    
    if not ml_files:
        print("No ML prediction files found")
        return pd.DataFrame()
    
    all_dfs = []
    for file_path in ml_files:
        try:
            if file_path.endswith('.csv'):
                df = pd.read_csv(file_path)
            else:
                df = pd.read_excel(file_path)
            
            print(f"Loaded: {Path(file_path).name} ({len(df)} rows)")
            all_dfs.append(df)
        except Exception as e:
            print(f" Error reading {Path(file_path).name}: {e}")
    
    if all_dfs:
        df_ml = pd.concat(all_dfs, ignore_index=True)
        print(f"Total ML entries: {len(df_ml)}")
        return df_ml
    
    return pd.DataFrame()

def calculate_comparison_metrics(df):
    """Calculate comparison metrics between ML and structural SASA."""
    
    # Find ML SASA column
    ml_col = None
    for col in df.columns:
        col_lower = col.lower()
        if any(keyword in col_lower for keyword in ['predict', 'ml_sasa', 'estimated']):
            if 'sasa' in col_lower:
                ml_col = col
                break
    
    struct_col = 'Structural_SASA_Å2'
    
    if ml_col and struct_col in df.columns:
        # Remove rows where either value is missing
        mask = df[ml_col].notna() & df[struct_col].notna()
        comparison_df = df[mask].copy()
        
        if len(comparison_df) > 0:
            # Calculate errors
            comparison_df['SASA_Absolute_Error'] = abs(
                comparison_df[ml_col] - comparison_df[struct_col]
            )
            comparison_df['SASA_Relative_Error_%'] = (
                (comparison_df['SASA_Absolute_Error'] / comparison_df[struct_col]) * 100
            ).round(2)
            
            # Stats
            mae = comparison_df['SASA_Absolute_Error'].mean()
            mre = comparison_df['SASA_Relative_Error_%'].mean()
            rmse = np.sqrt((comparison_df['SASA_Absolute_Error']**2).mean())
            
            print(f"\n{'='*50}")
            print(f"COMPARISON STATISTICS (n={len(comparison_df)})")
            print(f"{'='*50}")
            print(f"Mean Absolute Error (MAE): {mae:.2f} Ų")
            print(f"Mean Relative Error (MRE): {mre:.2f}%")
            print(f"Root Mean Square Error (RMSE): {rmse:.2f} Ų")
            print(f"{'='*50}\n")
            
            # Copy metrics back to original dataframe
            for col_name in ['SASA_Absolute_Error', 'SASA_Relative_Error_%']:
                df[col_name] = comparison_df[col_name]
    
    return df

def run_comparison():
    print("="*60)
    print("ANTIBODY SASA COMPARISON: ML vs 3D STRUCTURAL")
    print("="*60)
    
    # 1. Load Sequence Data
    if not SEQUENCE_EXCEL.exists():
        print(f" ERROR: Cannot find {SEQUENCE_EXCEL}")
        return
    
    df_seq = pd.read_excel(SEQUENCE_EXCEL)
    print(f"\n Loaded {len(df_seq)} sequence entries")
    print(f"Columns: {', '.join(df_seq.columns[:5])}...")
    
    # 2. Load Structural Data
    df_struct = load_structural_sasa()
    
    if df_struct.empty:
        print("\n WARNING: No structural SASA data found!")
        print("  Check that 3D_structure_builder.py has run successfully")
    else:
        print(f"\n Loaded {len(df_struct)} structural SASA values")
    
    # 3. Load ML Predictions
    df_ml = load_ml_predictions()
    
    if df_ml.empty:
        print("\n WARNING: No ML prediction data found!")
        print("  Check that ml_sasa_predictor_chains.py has run successfully")
    
    # 4. Merge Everything
    df_final = df_seq.copy()
    
    if not df_struct.empty:
        df_final = pd.merge(
            df_final, 
            df_struct, 
            on="Antibody_Name", 
            how="left"
        )
        print(f" Merged structural data")
    
    if not df_ml.empty:
        df_final = pd.merge(
            df_final, 
            df_ml, 
            on="Antibody_Name", 
            how="left",
            suffixes=('', '_ML')
        )
        print(f" Merged ML prediction data")
    
    # 5. Calculate Comparison Metrics
    if not df_struct.empty and not df_ml.empty:
        df_final = calculate_comparison_metrics(df_final)
    
    # 6. Calculate Aggregation Risk
    if 'Structural_SASA_Å2' in df_final.columns:
        if 'Sequence_Length_Total_AA' in df_final.columns:
            df_final['SASA_per_Residue'] = (
                df_final['Structural_SASA_Å2'] / df_final['Sequence_Length_Total_AA']
            ).round(2)
            
            if 'GRAVY_Score' in df_final.columns:
                df_final['Aggregation_Risk_Index'] = (
                    df_final['GRAVY_Score'] * df_final['SASA_per_Residue']
                ).round(4)
                df_final = df_final.sort_values(
                    by='Aggregation_Risk_Index', 
                    ascending=False
                )
    
    # 7. Save Report
    df_final.to_excel(FINAL_REPORT_PATH, index=False)
    
    print(f"\n{'='*60}")
    print("FINAL REPORT SUMMARY")
    print(f"{'='*60}")
    print(f"Total antibodies: {len(df_final)}")
    if 'Structural_SASA_Å2' in df_final.columns:
        struct_count = df_final['Structural_SASA_Å2'].notna().sum()
        print(f"With structural data: {struct_count}")
    
    ml_cols = [c for c in df_final.columns if 'predict' in c.lower() or 'ml' in c.lower()]
    if ml_cols:
        ml_count = df_final[ml_cols[0]].notna().sum()
        print(f"With ML predictions: {ml_count}")
    
    print(f"\n Report saved: {FINAL_REPORT_PATH}")
    print(f"{'='*60}\n")

if __name__ == "__main__":
    run_comparison()