caplacizumab = """
>Caplacizumab_VWF_Heavy_Chain_1
EVQLVESGGGLVQPGGSLRLSCAASGRTFSYNPMGWFRQAPGKGRELVAAISRTGGSTYYPDSVEGRFTISRDNAKRMVYLQMNSLRAEDTAVYYCAAAGVRAEDGRVRTLPSEYTFWGQGTQVTVSS
>Caplacizumab_VWF_Light_Chain_1
na
"""
